# Generated by Django 2.0.7 on 2018-07-17 07:47

import ckeditor.fields
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Baiviet',
            fields=[
                ('ma_bai', models.AutoField(primary_key=True, serialize=False)),
                ('tieu_de', models.CharField(max_length=50)),
                ('noi_dung', ckeditor.fields.RichTextField(verbose_name='Soạn thảo theo cách của riêng bạn')),
                ('ngay_tao', models.DateField(default=datetime.datetime(2018, 7, 17, 14, 47, 34, 297832), verbose_name='Date')),
            ],
        ),
        migrations.CreateModel(
            name='Danhmuc',
            fields=[
                ('ma_loai', models.AutoField(primary_key=True, serialize=False)),
                ('ten_loai', models.CharField(max_length=50)),
                ('mo_ta', ckeditor.fields.RichTextField(verbose_name='Soạn thảo theo cách của riêng bạn')),
                ('ngay_tao', models.DateField(default=datetime.datetime(2018, 7, 17, 14, 47, 34, 297832), verbose_name='Date')),
            ],
        ),
        migrations.CreateModel(
            name='Nguoidung',
            fields=[
                ('ten_dang_nhap', models.AutoField(primary_key=True, serialize=False)),
                ('mat_khau', models.CharField(max_length=15)),
                ('ho_ten', models.CharField(max_length=50)),
                ('email', models.EmailField(blank=True, max_length=70)),
                ('gioi_tinh', models.CharField(max_length=7)),
                ('anh_dai_dien', models.CharField(max_length=200)),
                ('quyen', models.CharField(max_length=10)),
                ('trang_thai', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Quyen',
            fields=[
                ('ma_quyen', models.AutoField(primary_key=True, serialize=False)),
                ('quyen_han', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='danhmuc',
            name='nguoi_tao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Nguoidung'),
        ),
        migrations.AddField(
            model_name='baiviet',
            name='danh_muc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Danhmuc'),
        ),
        migrations.AddField(
            model_name='baiviet',
            name='tac_gia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Nguoidung'),
        ),
    ]
