# Generated by Django 2.0.7 on 2018-07-18 04:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20180718_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baiviet',
            name='ngay_tao',
            field=models.DateField(default=datetime.datetime(2018, 7, 18, 4, 19, 51, 434772, tzinfo=utc), verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='danhmuc',
            name='ngay_tao',
            field=models.DateField(default=datetime.datetime(2018, 7, 18, 4, 19, 51, 430770, tzinfo=utc), verbose_name='Date'),
        ),
    ]
