# Generated by Django 2.0.7 on 2018-07-18 05:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_auto_20180718_1119'),
    ]

    operations = [
        migrations.RenameField(
            model_name='danhmuc',
            old_name='ma_loai',
            new_name='ma_danhmuc',
        ),
        migrations.RenameField(
            model_name='danhmuc',
            old_name='ten_loai',
            new_name='ten_danhmuc',
        ),
        migrations.AddField(
            model_name='nguoidung',
            name='mailactive',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='baiviet',
            name='ngay_tao',
            field=models.DateField(default=datetime.datetime(2018, 7, 18, 4, 57, 17, 752540, tzinfo=utc), verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='danhmuc',
            name='ngay_tao',
            field=models.DateField(default=datetime.datetime(2018, 7, 18, 4, 57, 17, 752540, tzinfo=utc), verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='nguoidung',
            name='email',
            field=models.EmailField(blank=True, max_length=70, unique=True),
        ),
        migrations.AlterField(
            model_name='nguoidung',
            name='trang_thai',
            field=models.CharField(max_length=10),
        ),
    ]
