# Generated by Django 2.0.7 on 2018-07-19 07:14

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_auto_20180719_1332'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nguoidung',
            name='quyen',
        ),
        migrations.AddField(
            model_name='nguoidung',
            name='loai_user',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='web.Loaiuser'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='baiviet',
            name='ngay_tao',
            field=models.DateField(default=datetime.datetime(2018, 7, 19, 7, 14, 1, 726475, tzinfo=utc), verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='danhmuc',
            name='ngay_tao',
            field=models.DateField(default=datetime.datetime(2018, 7, 19, 7, 14, 1, 726475, tzinfo=utc), verbose_name='Date'),
        ),
    ]
