# Generated by Django 2.0.7 on 2018-07-23 01:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_auto_20180719_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='danhmuc',
            name='is_menu',
            field=models.CharField(default='yes', max_length=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='baiviet',
            name='ngay_tao',
            field=models.DateField(default=datetime.datetime(2018, 7, 23, 1, 10, 6, 975146, tzinfo=utc), verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='danhmuc',
            name='ngay_tao',
            field=models.DateField(default=datetime.datetime(2018, 7, 23, 1, 10, 6, 975146, tzinfo=utc), verbose_name='Date'),
        ),
    ]
