# Generated by Django 2.0.7 on 2018-07-23 04:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_auto_20180723_1137'),
    ]

    operations = [
        migrations.AddField(
            model_name='danhmuc',
            name='ngay_sua',
            field=models.DateField(default=datetime.date(2018, 7, 23), verbose_name='Date'),
        ),
    ]
