# Generated by Django 2.0.7 on 2018-07-26 02:24

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0014_auto_20180724_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baiviet',
            name='ngay_tao',
            field=models.DateField(default=datetime.date(2018, 7, 26), verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='baiviet',
            name='tac_gia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='web.Nguoidung'),
        ),
        migrations.AlterField(
            model_name='danhmuc',
            name='ngay_sua',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='danhmuc',
            name='ngay_tao',
            field=models.DateField(),
        ),
    ]
