# Generated by Django 2.0.7 on 2018-07-30 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0018_auto_20180726_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baiviet',
            name='tieu_de',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
