# Generated by Django 2.0.7 on 2018-07-30 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0019_auto_20180730_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baiviet',
            name='tieu_de',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='nguoidung',
            name='anh_dai_dien',
            field=models.FileField(upload_to='uploads'),
        ),
    ]
