# Generated by Django 2.0.7 on 2018-07-30 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0020_auto_20180730_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baiviet',
            name='tieu_de',
            field=models.CharField(max_length=200),
        ),
    ]
