# Generated by Django 2.0.7 on 2018-07-30 07:14

from django.db import migrations, models
import datetime

class Migration(migrations.Migration):

    dependencies = [
        ('web', '0021_auto_20180730_1123'),
    ]

    operations = [
        migrations.AddField(
            model_name='baiviet',
            name='ngay_sua',
            field=models.DateField(auto_now_add=True, default=datetime.date(2018, 7, 24), verbose_name='Date'),
            preserve_default=False,
        ),
    ]
