# Generated by Django 2.0.7 on 2018-08-01 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0022_baiviet_ngay_sua'),
    ]

    operations = [
        migrations.AddField(
            model_name='nguoidung',
            name='xacnhan',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='baiviet',
            name='ngay_sua',
            field=models.DateField(auto_now_add=True),
        ),
    ]
