# Generated by Django 2.0.7 on 2018-08-01 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0023_auto_20180801_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baiviet',
            name='ngay_sua',
            field=models.DateField(),
        ),
    ]
