# Generated by Django 2.0.7 on 2018-08-08 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0025_auto_20180807_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nguoidung',
            name='email',
            field=models.EmailField(max_length=70, unique=True),
        ),
    ]
