# Generated by Django 2.0.7 on 2018-08-10 02:09

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0026_auto_20180808_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baiviet',
            name='noi_dung',
            field=ckeditor.fields.RichTextField(verbose_name=''),
        ),
        migrations.AlterField(
            model_name='baiviet',
            name='tin_hot',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='baiviet',
            name='trang_thai',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='danhmuc',
            name='is_menu',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='nguoidung',
            name='trang_thai',
            field=models.BooleanField(default=False),
        ),
    ]
