# Generated by Django 2.0.7 on 2018-08-10 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0027_auto_20180810_0909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baiviet',
            name='ngay_sua',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='baiviet',
            name='ngay_tao',
            field=models.DateTimeField(),
        ),
    ]
