# Generated by Django 2.0.7 on 2018-08-10 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0028_auto_20180810_1625'),
    ]

    operations = [
        migrations.RenameField(
            model_name='baiviet',
            old_name='danh_muc',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='baiviet',
            old_name='noi_dung',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='baiviet',
            old_name='ngay_sua',
            new_name='datetime_created',
        ),
        migrations.RenameField(
            model_name='baiviet',
            old_name='ngay_tao',
            new_name='datetime_updated',
        ),
        migrations.RenameField(
            model_name='baiviet',
            old_name='ma_bai',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='baiviet',
            old_name='tin_hot',
            new_name='is_hot',
        ),
        migrations.RenameField(
            model_name='baiviet',
            old_name='trang_thai',
            new_name='is_locked',
        ),
        migrations.RenameField(
            model_name='baiviet',
            old_name='tieu_de',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='baiviet',
            old_name='tac_gia',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='baiviet',
            old_name='luot_xem',
            new_name='views',
        ),
    ]
