# Generated by Django 2.0.7 on 2018-08-13 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0029_auto_20180810_1634'),
    ]

    operations = [
        migrations.RenameField(
            model_name='danhmuc',
            old_name='ngay_tao',
            new_name='datetime_created',
        ),
        migrations.RenameField(
            model_name='danhmuc',
            old_name='ngay_sua',
            new_name='datetime_updated',
        ),
        migrations.RenameField(
            model_name='danhmuc',
            old_name='mo_ta',
            new_name='describe',
        ),
        migrations.RenameField(
            model_name='danhmuc',
            old_name='ma_danhmuc',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='danhmuc',
            old_name='ten_danhmuc',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='danhmuc',
            old_name='is_menu',
            new_name='show_as_menu',
        ),
        migrations.RenameField(
            model_name='danhmuc',
            old_name='nguoi_tao',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='loaiuser',
            old_name='ma_loai',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='loaiuser',
            old_name='ten_loai',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='nguoidung',
            old_name='anh_dai_dien',
            new_name='avatar_url',
        ),
        migrations.RenameField(
            model_name='nguoidung',
            old_name='ho_ten',
            new_name='fullname',
        ),
        migrations.RenameField(
            model_name='nguoidung',
            old_name='gioi_tinh',
            new_name='gender',
        ),
        migrations.RenameField(
            model_name='nguoidung',
            old_name='loai_user',
            new_name='group',
        ),
        migrations.RenameField(
            model_name='nguoidung',
            old_name='trang_thai',
            new_name='is_locked',
        ),
        migrations.RenameField(
            model_name='nguoidung',
            old_name='mat_khau',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='nguoidung',
            old_name='ten_dang_nhap',
            new_name='username',
        ),
    ]
