# Generated by Django 2.0.7 on 2018-08-13 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0030_auto_20180813_0858'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Danhmuc',
            new_name='categories',
        ),
        migrations.RenameModel(
            old_name='Loaiuser',
            new_name='groups',
        ),
        migrations.RenameModel(
            old_name='Baiviet',
            new_name='posts',
        ),
        migrations.RenameModel(
            old_name='Nguoidung',
            new_name='users',
        ),
    ]
