# Generated by Django 2.0.7 on 2018-08-13 02:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0031_auto_20180813_0906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='datetime_created',
            field=models.DateField(default=datetime.datetime(2018, 8, 13, 2, 9, 2, 642116, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='categories',
            name='datetime_updated',
            field=models.DateField(default=datetime.datetime(2018, 8, 13, 2, 9, 2, 642116, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='posts',
            name='datetime_created',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 13, 2, 9, 2, 642116, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='posts',
            name='datetime_updated',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 13, 2, 9, 2, 642116, tzinfo=utc)),
        ),
    ]
