# Generated by Django 2.0.7 on 2018-08-13 03:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0035_auto_20180813_1039'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='mailactive',
            new_name='status',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='xacnhan',
            new_name='token',
        ),
        migrations.AlterField(
            model_name='categories',
            name='datetime_created',
            field=models.DateField(default=datetime.datetime(2018, 8, 13, 3, 57, 57, 193305, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='categories',
            name='datetime_updated',
            field=models.DateField(default=datetime.datetime(2018, 8, 13, 3, 57, 57, 193305, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='posts',
            name='datetime_created',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 13, 3, 57, 57, 193305, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='posts',
            name='datetime_updated',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 13, 3, 57, 57, 193305, tzinfo=utc)),
        ),
    ]
