# Generated by Django 2.0.7 on 2018-08-13 03:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0036_auto_20180813_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='datetime_created',
            field=models.DateField(default=datetime.datetime(2018, 8, 13, 3, 59, 13, 268376, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='categories',
            name='datetime_updated',
            field=models.DateField(default=datetime.datetime(2018, 8, 13, 3, 59, 13, 268376, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='posts',
            name='datetime_created',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 13, 3, 59, 13, 268376, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='posts',
            name='datetime_updated',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 13, 3, 59, 13, 268376, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='users',
            name='status',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='users',
            name='token',
            field=models.CharField(max_length=200),
        ),
    ]
