# Generated by Django 2.0.7 on 2018-08-13 10:18

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0038_auto_20180813_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='datetime_created',
            field=models.DateField(default=datetime.datetime(2018, 8, 13, 10, 18, 1, 601047, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='categories',
            name='datetime_updated',
            field=models.DateField(default=datetime.datetime(2018, 8, 13, 10, 18, 1, 601047, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='posts',
            name='datetime_created',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 13, 10, 18, 1, 601047, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='posts',
            name='datetime_updated',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 13, 10, 18, 1, 601047, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='posts',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.users'),
        ),
    ]
