# Generated by Django 2.0.7 on 2018-08-14 01:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0039_auto_20180813_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='datetime_created',
            field=models.DateField(default=datetime.datetime(2018, 8, 14, 1, 15, 51, 945152, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='categories',
            name='datetime_updated',
            field=models.DateField(default=datetime.datetime(2018, 8, 14, 1, 15, 51, 945152, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='posts',
            name='datetime_created',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 14, 1, 15, 51, 946149, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='posts',
            name='datetime_updated',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 14, 1, 15, 51, 946149, tzinfo=utc)),
        ),
    ]
