# Generated by Django 2.0.7 on 2018-08-14 03:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0040_auto_20180814_0815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='datetime_created',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 14, 3, 30, 45, 134615, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='categories',
            name='datetime_updated',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 14, 3, 30, 45, 134615, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='categories',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='posts',
            name='datetime_created',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 14, 3, 30, 45, 134615, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='posts',
            name='datetime_updated',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 14, 3, 30, 45, 134615, tzinfo=utc)),
        ),
    ]
